spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhuishusecurity?characterEncoding=utf-8&useSSL=false
    username: root
    password: 126668
#  redis:
#     host: 123.206.190.163
#     port: 6379
  session:
    store-type: redis
  redis:
      port: 6379
      host: 127.0.0.1
  rabbitmq:
    host:
    cache:
      channel:
        size:

server:
  port: 8086
 # port: 80
security:
  basic:
    enabled: true
  oauth2:
    client:
      client-id: longzzai
      client-secret: longzzaisecret
longzzai:
  security:
    browser:
      login-type: json
      remember-me-seconds: 60
      sign-up-page: /demo-signUp.html
    social:
      oauth2:
        clients[0]:
          client-id: longzzai
          client-secret: longzzaisecret
        clients[1]:
          client-id: test
          client-secret: test
          expire-in: 60
          scopes[0]: all
          scopes[1]: read
          scopes[2]: write
        store-type: jwttoken
      qq:
        app-id: 101443937
        app-secret: 5883a6286c35b82872c58b15d79bd288
        provider-id: qq
        filter-processes-url: /auth
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        filter-processes-url: /auth
        provider-id: weixin
    session:
      max-sessions-prevents-login: true
      maximum-sessions: 1